project:
  type: book
  output-dir: docs
  
book:
  title: "title"
  date: "October"
  chapters: 
    - index.qmd
    - disturbance_prediction

  
format:
  html:
    theme: cosmo
    code-link: TRUE

